[package]
name = "manual-http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buf-list = "1.0"
bytes = "1.4"
memchr = "2.5"
sha2 = "0.10"
url = "2.4"
